src/elf_ops.c, src/elf_ops.h, src/gotcha.c, src/gotcha_auxv.c, src/gotcha_auxv.h, src/gotcha_utils.c, src/hash.c, src/libc_wrappers.h, src/tool.c
- Build fixes for when building against glibc.
- Warning cleanup
- Move default to be against glibc (for now)
=> Fixes when building against 

README.md
#7 only fixed the codecov link.
=> Fixed badge link URL

src/libc_wrappers.c, src/libc_wrappers.h, test/unit/gotcha_unit_tests.c
Adds tests, and accompanying bug fixes, for gotcha's internal printf
=> printf tests

src/example/minimal/sampleLib.c, src/example/minimal/symbolLookup.c, test/hammer/CMakeLists.txt
Added in the hammer test to our cmake testing (Travis now checks it)
=> Updated testing

src/CMakeLists.txt
@daboehme , 👍 ? Or anything else needed immediately?
=> Fixed up CMake as per @daboehme 's suggestion

README.md
I've created a sample gotcha project which generates a tracer.
=> Added link to gotcha-tracer example project

include/gotcha/gotcha_types.h
=> Updated struct and enum definitions

.travis.yml
Somebody who will remain anonymous (@davidpoliakoff) broke the codecov integration. Oops. This fixes it
=> Re-enabling Codecov

CMakeLists.txt, README.md
This branch contains the changes needed to declare a Gotcha 1.0 release
=> Release 1.0

.travis.yml, include/gotcha/gotcha_types.h, src/example/minimal/sampleLib.c, src/gotcha.c, src/tool.c, test/hammer/gen.cc, test/hammer/math.hpp, test/hammer/wrap.cc, test/hammer/wrap.h, test/unit/gotcha_unit_tests.c
=> Updated types, removed all references to opaque handle

include/gotcha/gotcha.h, src/library_filters.c, src/library_filters.h
@mplegendre I tried to follow the name convention to expose these library filter functions. Let me if you need more changes.
=> Expose library filter interface

src/CMakeLists.txt
- The absence of this is causing my spack builds to fail
=> Added installation include directory

test/CMakeLists.txt
As explained in #108. Some tests never pass and some tests pass intermittently. 
This needs more investigation.
=> Disabling tests which are currently failing

test/CMakeLists.txt, test/rogot/autotee.c
=> fix readonly_got_table test.

.github/workflows/build-and-test.yaml
ignore test and example from coverage.
=> ignore test and example from coverage.

test/CMakeLists.txt, test/filter/CMakeLists.txt, test/filter/num.c, test/filter/num.h, test/filter/test_filter.c
Added coverage for filter functions.
=> Improve coverage of filter functions in GOTCHA

src/elf_ops.c, src/elf_ops.h, src/gotcha.c, test/CMakeLists.txt, test/symver/CMakeLists.txt, test/symver/retX.h, test/symver/retX_new.c, test/symver/retX_old.c, test/symver/symver.map, test/symver/test_symver.c
=> Search for the latest symbol version

.github/workflows/build-and-test.yaml, src/elf_ops.c, src/gotcha.c, src/gotcha_auxv.c, src/gotcha_dl.c, src/gotcha_utils.c, src/hash.c, src/libc_wrappers.c, src/tool.c, src/translations.c, test/dlopen/test_dlopen.c, test/filter/test_filter.c, test/unit/CMakeLists.txt, test/unit/gotcha_unit_tests.c, test/unit/testing_lib.c, test/unit/testing_lib.h
1. Some codes will be unreachable due to FS specific error. I ignored them on coverage.
2. Added tests for rest of the cases.
Depends on #122
=> Improve coverage of our code.

src/gotcha.c
The PR fixes the GOT Table calculation from program headers. The current code fails on cases where system loads a library in a non-zero address.
=> Fixed calculation for readonly got table.

src/gotcha.c
Currently, both GOT and PLT GOT are marked separately. Fixing the logic would improve performance.
=> Combining marking GOT and PLT GOT writable

docs/conf.py
Solves https://github.com/LLNL/GOTCHA/issues/134
=> Specify docs are in English

.github/docker/fedora.dockerfile, .github/workflows/build-and-test.yaml
Closes https://github.com/LLNL/GOTCHA/issues/140
=> Add build on latest fedora
